# -*- coding: utf-8 -*-
"""Captsone_Group_1006_Year_2020.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vOU3O7OA2AGceQTQ68JWXrs4vrf7Pg2B
"""

!pip install -q mysql-connector-python

!pip install mysql-connector-python

import mysql.connector

db = mysql.connector.connect(host='cpanel.insaid.co',
                             database='Capstone1',
                             user='student',
                             password='student')

print(db)

cur=""
cur = db.cursor()

cur.execute("SHOW TABLES")

tables = cur.fetchall()

print(tables)



query = """ SELECT * FROM gender_age_train"""

cur.execute(query)

x=cur.fetchall()

print(x)

NotebookApp.iopub_data_rate_limit=1000000.0 
NotebookApp.rate_limit_window=3.0

import pandas as pd

df1 = pd.DataFrame(x, columns=['device_id','gender','age','group'])

df1.shape

query = """ SELECT * FROM phone_brand_device_model"""

cur.execute(query)

x=cur.fetchall()

df2 = pd.DataFrame(x, columns=['device_id','brand','model'])

df2.shape

df2

db_events = pd.read_csv('drive/My Drive/Capstone_Group_1006_Year_2020/events_data.csv')
#db_events = pd.read_csv('events_data.csv')
#/content/drive/My Drive/Capstone_Group_1006_Year_2020/events_data.csv

db_events.shape

db_events.head()